---
- hosts: all
  become: yes
  vars:
    hello: world
  tasks:
    - name: install things
      apt:
        name: "{{ item }}"
        update_cache: yes
      with_items:
        - python3.4 
        - python3-numpy 
        - python3-scipy
        - python3-matplotlib
        - python3-pandas
        - python-nltk
        - ipython3
        - xcb-proto
